require 'bound/builtin_record_types/a'
require 'bound/builtin_record_types/aaaa'
require 'bound/builtin_record_types/txt'
require 'bound/builtin_record_types/mx'
require 'bound/builtin_record_types/cname'
require 'bound/builtin_record_types/ns'
